/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmployeeDetailsObjectPageObjectPage journey");

        opaTest("Navigate to EmployeeDetailsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheEmployeeDetailsList.onFilterBar().iExecuteSearch();

            Then.onTheEmployeeDetailsList.onTable().iCheckRows();
            When.onTheEmployeeDetailsList.onTable().iPressRow(0);

            Then.onTheEmployeeDetailsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheEmployeeDetailsObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpId" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpFirstName" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpLastName" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpDeptName" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpLoc" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpSalary" });
            Then.onTheEmployeeDetailsObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpRole" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});