/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmployeeDetailsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheEmployeeDetailsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheEmployeeDetailsList.onFilterBar().iCheckFilterField("EmpFirstName");
            Then.onTheEmployeeDetailsList.onFilterBar().iCheckFilterField("EmpRole");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheEmployeeDetailsList.onTable().iCheckColumns(undefined, {"EmpId":{"header":"Employee Id"},"EmpFirstName":{"header":"Employee First Name"},"EmpLastName":{"header":"Employee Last Name"},"EmpDeptName":{"header":"Employee Department Name"},"EmpLoc":{"header":"Employee Location"},"EmpSalary":{"header":"Employee Salary"},"EmpRole":{"header":"Employee Role"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheEmployeeDetailsList.onFilterBar().iExecuteSearch();
            
            Then.onTheEmployeeDetailsList.onTable().iCheckRows();

            When.onTheEmployeeDetailsList.onTable().iPressRow(0);
            Then.onTheEmployeeDetailsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});